name: CI

on:
  # Compare the last commit of main -> to the current commit of a PR branch.
  # (Note: To compare changes between the current commit to the last pushed remote commit of a PR branch set `since_last_remote_commit: true`)
  pull_request:
    paths:
      - "data/**"

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Check changed files
        env:
          FILENAMES: ${{ steps.changed-files.outputs.all_changed_files }}
          USERNAME: ${{ github.actor }}
        run: |
          npm start
